steps:
  # Create a volume to store Maven artifacts
  - name: 'gcr.io/cloud-builders/docker'
    args: ['volume', 'create', 'maven-repo']

  # Maven build with volume mount
  - name: 'gcr.io/cloud-builders/maven'
    args: ['clean', 'install', '-DskipTests']
    volumes:
      - name: 'maven-repo'
        path: '/root/.m2'
    
  # List the target directory to verify JAR file exists
  - name: 'ubuntu'
    args: ['ls', '-la', 'target/']
    
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_DEPLOY_REGION'
options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'MAVEN_OPTS=-Dmaven.repo.local=/workspace/.m2/repository'

images: [gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA]